[package]
name = "dioxus_markdown"
version = "0.3.0-alpha.1"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/jprider63/dioxus.git", rev="cd3ff6d3644347163c249da8293a76db02044d03" }
pulldown-cmark = "0.9.3"

[dev-dependencies]
dioxus = { git = "https://github.com/jprider63/dioxus.git", rev="cd3ff6d3644347163c249da8293a76db02044d03", features = ["desktop"] }
